/*.$file${.::pomodoro.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: pomodoro-timer.qm
* File:  ${.::pomodoro.c}
*
* This code has been generated by QM 5.1.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${.::pomodoro.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"    /* QP/C framework API */
#include "bsp.h"    /* Board Support Package interface */

/* ask QM to declare the Pomodoro class ------------------------------------*/
/*.$declare${AOs::Pomodoro} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Pomodoro} ........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt timeEvt;
} Pomodoro;

/* protected: */
static QState Pomodoro_initial(Pomodoro * const me, void const * const par);
static QState Pomodoro_show_stats(Pomodoro * const me, QEvt const * const e);
static QState Pomodoro_timing(Pomodoro * const me, QEvt const * const e);
static QState Pomodoro_short_break(Pomodoro * const me, QEvt const * const e);
static QState Pomodoro_long_break(Pomodoro * const me, QEvt const * const e);
static QState Pomodoro_pomodoro(Pomodoro * const me, QEvt const * const e);
/*.$enddecl${AOs::Pomodoro} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* instantiate the Pomodoro active object ----------------------------------*/
static Pomodoro l_pomodoro;
QActive * const AO_Pomodoro = &l_pomodoro.super;

/* ask QM to define the Pomodoro class -------------------------------------*/
/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::Pomodoro_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Pomodoro_ctor} ...................................................*/
void Pomodoro_ctor(void) {
    Pomodoro *me = (Pomodoro *)AO_Pomodoro;
    QActive_ctor(&me->super, Q_STATE_CAST(&Pomodoro_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
/*.$enddef${AOs::Pomodoro_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::Pomodoro} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Pomodoro} ........................................................*/
/*.${AOs::Pomodoro::SM} ....................................................*/
static QState Pomodoro_initial(Pomodoro * const me, void const * const par) {
    /*.${AOs::Pomodoro::SM::initial} */
    QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC/2,
                 BSP_TICKS_PER_SEC/2);
    return Q_TRAN(&Pomodoro_show_stats);
}
/*.${AOs::Pomodoro::SM::show_stats} ........................................*/
static QState Pomodoro_show_stats(Pomodoro * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::Pomodoro::SM::show_stats::ORIENT_LB} */
        case ORIENT_LB_SIG: {
            status_ = Q_TRAN(&Pomodoro_long_break);
            break;
        }
        /*.${AOs::Pomodoro::SM::show_stats::ORIENT_SB} */
        case ORIENT_SB_SIG: {
            status_ = Q_TRAN(&Pomodoro_short_break);
            break;
        }
        /*.${AOs::Pomodoro::SM::show_stats::ORIENT_P} */
        case ORIENT_P_SIG: {
            status_ = Q_TRAN(&Pomodoro_pomodoro);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.${AOs::Pomodoro::SM::timing} ............................................*/
static QState Pomodoro_timing(Pomodoro * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::Pomodoro::SM::timing::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Pomodoro_show_stats);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.${AOs::Pomodoro::SM::timing::short_break} ...............................*/
static QState Pomodoro_short_break(Pomodoro * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&Pomodoro_timing);
            break;
        }
    }
    return status_;
}
/*.${AOs::Pomodoro::SM::timing::long_break} ................................*/
static QState Pomodoro_long_break(Pomodoro * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&Pomodoro_timing);
            break;
        }
    }
    return status_;
}
/*.${AOs::Pomodoro::SM::timing::pomodoro} ..................................*/
static QState Pomodoro_pomodoro(Pomodoro * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&Pomodoro_timing);
            break;
        }
    }
    return status_;
}
/*.$enddef${AOs::Pomodoro} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
